services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: yourUsername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourPassword
      - key: WEBHOOK_URL
        value: https://your-service.onrender.com
      - key: N8N_USER_FOLDER
        value: /var/data/.n8n 