services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true